project_id = "gloto"

[functions.crear-cuenta-negocio]
verify_jwt = true

[functions.eliminar-cuenta-negocio]
verify_jwt = true

[functions.restablecer-contrasena-negocio]
verify_jwt = true

[functions.crear-cuenta-domiciliario]
verify_jwt = false
