export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-variant": "#353535",
        "secondary-fixed": "#e8ddff",
        "on-background": "#e5e2e1",
        background: "#131313",
        tertiary: "#c9c6c5",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#cebdff",
        "on-primary-fixed": "#25005a",
        "tertiary-container": "#686666",
        "on-tertiary-fixed-variant": "#474646",
        "on-surface-variant": "#ccc3d8",
        "secondary-container": "#4f319c",
        "on-primary-container": "#ede0ff",
        "surface-bright": "#393939",
        "error-container": "#93000a",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed": "#e5e2e1",
        error: "#ffb4ab",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        "on-tertiary": "#313030",
        primary: "#d2bbff",
        "on-secondary-container": "#bea8ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-fixed": "#21005e",
        secondary: "#cebdff",
        "outline-variant": "#4a4455",
        "on-error": "#690005",
        outline: "#958da1",
        "on-primary": "#3f008e",
        "primary-fixed": "#eaddff",
        "on-tertiary-container": "#e8e5e4",
        "inverse-primary": "#732ee4",
        "on-secondary": "#381385",
        "surface-dim": "#131313",
        "surface-container-highest": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#4f319c",
        "surface-container": "#20201f",
        surface: "#131313",
        "surface-tint": "#d2bbff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        xs: "4px",
        md: "16px",
        "margin-desktop": "48px",
        xl: "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        unit: "4px",
        sm: "8px",
      },
      fontFamily: {
        "label-caps": ["Inter"],
        h1: ["Manrope"],
        h3: ["Manrope"],
        "body-md": ["Inter"],
        code: ["monospace"],
        "body-lg": ["Inter"],
        h2: ["Manrope"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        h1: [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h3: [
          "24px",
          { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        h2: [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
